server:
  port: 8084
spring:
  application:
    name: searchservice
  cloud:
    nacos:
      server-addr: localhost:8848
  rabbitmq:
    host: 192.168.244.130
    port: 5672
    virtual-host: /
    username: root
    password: root
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS